# Generated by Django 5.0.1 on 2024-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=60, null=True)),
                ('specialization', models.CharField(blank=True, max_length=60, null=True)),
                ('current_position', models.CharField(blank=True, max_length=60, null=True)),
                ('work_experience', models.CharField(blank=True, db_column='Work_experience', max_length=60, null=True)),
                ('resume', models.CharField(blank=True, max_length=60, null=True)),
                ('contactid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=45, null=True)),
                ('company_address', models.CharField(blank=True, max_length=256, null=True)),
                ('company_email', models.CharField(blank=True, max_length=45, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('company_fax', models.CharField(blank=True, max_length=45, null=True)),
                ('company_contactperson', models.CharField(blank=True, max_length=45, null=True)),
                ('company_country', models.CharField(blank=True, max_length=45, null=True)),
                ('company_state', models.CharField(blank=True, max_length=45, null=True)),
                ('company_currency', models.CharField(blank=True, max_length=60, null=True)),
                ('company_language', models.CharField(blank=True, max_length=45, null=True)),
                ('company_code', models.CharField(blank=True, max_length=45, null=True)),
                ('company_timezone', models.CharField(blank=True, max_length=60, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('candidateid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_middlename', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_joiningdate', models.DateField(blank=True, null=True)),
                ('employee_qualification', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_totalexperiance', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_dob', models.DateField(blank=True, null=True)),
                ('employee_gender', models.CharField(blank=True, db_comment='1=>Male,2=>Female', max_length=10, null=True)),
                ('employee_address1', models.CharField(blank=True, max_length=256, null=True)),
                ('employee_address2', models.CharField(blank=True, max_length=256, null=True)),
                ('employee_country', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_state', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_city', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_pincode', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('employee_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('employee_email', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_photo', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_status', models.CharField(blank=True, db_comment='1=>existing,2=>resigned,3=>terminated', max_length=45, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(blank=True, db_column='ActivityName', max_length=60, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('icon', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engine_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(blank=True, db_column='ModuleName', max_length=60, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engine_module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineSubmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submodulename', models.CharField(blank=True, db_column='SubModuleName', max_length=60, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('icon', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engine_submodule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype_id', models.IntegerField(blank=True, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('submodule_id', models.IntegerField(blank=True, null=True)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('e_read', models.CharField(blank=True, max_length=10, null=True)),
                ('e_write', models.CharField(blank=True, max_length=10, null=True)),
                ('e_update', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('activkey', models.CharField(max_length=128)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('lastvisit_at', models.DateTimeField(blank=True, null=True)),
                ('superuser', models.IntegerField()),
                ('status', models.IntegerField()),
                ('usertypeid', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('companyid', models.IntegerField(blank=True, null=True)),
                ('doctorid', models.IntegerField(blank=True, null=True)),
                ('patientid', models.IntegerField(blank=True, null=True)),
                ('adminid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype_name', models.CharField(blank=True, max_length=45, null=True)),
                ('financialyearid', models.IntegerField(blank=True, null=True)),
                ('companyid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usertype',
                'managed': False,
            },
        ),
    ]
