# Generated by Django 5.1.7 on 2025-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_admins_appointments_associates_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('person_name', models.CharField(max_length=255)),
                ('person_dob', models.DateField()),
                ('person_phone', models.CharField(max_length=20)),
                ('person_email', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('meet_person_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointment1',
                'managed': False,
            },
        ),
    ]
